global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: microservice
    metrics_path: /metrics
    honor_labels: false
    honor_timestamps: true
    sample_limit: 0
    scheme: http
    static_configs:
      - targets:
          # - host.docker.internal:9000
          # - host.docker.internal:9001
          - localhost:9000
          - localhost:9001
          - localhost:9002
